- palace/linalg/chebyshev.cpp
- palace/linalg/chebyshev.hpp
- palace/linalg/distrelaxation.cpp
- palace/linalg/distrelaxation.hpp
- palace/linalg/gmg.cpp
- palace/linalg/gmg.hpp
- palace/linalg/pc.cpp
- palace/linalg/pc.hpp
- palace/linalg/petsc.cpp
- palace/linalg/petsc.hpp
This showed up in particular when some processors have Nedelec space true dofs but none in the auxiliary space, so only showed up for distributed relaxation smoothing with geometric multigrid and super high MPI process counts.
> Fix bug when some processors own no degrees of freedom 

- cmake/extern/ExternalGitTags.cmake
- cmake/extern/ExternalPETSc.cmake
Pin SLEPc version so it is compatible with PETSc rather than pulling `main`.
> Fix SLEPc build in CMake superbuild

- .github/workflows/build-and-test-macos.yml
- .github/workflows/style.yml
Seems related to https://github.com/actions/runner-images/pull/7125.
Also simplify clang-format-15 install.
> Fix GitHub Actions `pkg-config` installation for macOS

- cmake/StaticAnalysisHelpers.cmake
> Compiler error fixes for `cppcheck` and `clang-tidy`

- examples/cavity/cavity.jl
- examples/cavity/convergence_study.jl
First of all, very exciting package! I noticed a couple of typos while looking at the examples, so thought to make a PR fixing them.
Fixes couple of typos in Julia examples.
> Fix typos in cavity and convergence examples

- docs/src/examples/rings.md
Typo in the rings doc, the `surface-M.csv` value quoted is not the computed value
> `surface-M.csv` value in docs is incorrect

- palace/deps/patch/mfem/patch_direct.diff
- palace/linalg/superlu.cpp
- palace/linalg/superlu.hpp
SuperLUSolver has a memory bug.
The parent class requires the usage of a pointer to the memory declared in the child class. Changing to a composition model ensures that the `mfem::SuperLUSolver` is deleted first, before the `Aint` variable has become invalid. This requires some changes to mfem branch too
Change from inheritance to composition. The class stores a `solver` variable and dispatches to it.
none.
> Fix SuperLUSolver memory bug

- palace/fem/farfieldboundaryoperator.cpp
- palace/fem/farfieldboundaryoperator.hpp
- palace/fem/spaceoperator.cpp
- palace/fem/spaceoperator.hpp
- palace/utils/mfemcoefficients.hpp
For boundary element integrals, the dimension of the curl is 1D in the reference space and thus the coefficient needs to be scalar for compatibility. For matrix-valued material properties, we need to use the normal-projected coefficient direction instead of the full matrix which is `space_dim x space_dim`.
Also updates `mfemcoefficients.hpp` classes to store small `mfem::Vector` and `mfem::Matrix` objects as member variables.
> Fix bug for second-order absorbing boundary condition

- examples/Project.toml
- examples/cavity/cavity.jl
- examples/cavity/convergence_study.jl
- palace/linalg/arpack.cpp
- palace/linalg/slepc.cpp
- scripts/format-source
- scripts/schema/ValidateConfig.jl
- scripts/validate-config
Fix a bug related to `examples/cavity/convergence_study.jl` where the coarsest hexahedral mesh had no non-boundary dofs for the `order=1` case. Also better Julia package dependency management utilities in `scripts/`.
Resolves #27
> Updates to Julia code for `examples/` and `scripts`

- .github/workflows/build-and-test-linux.yml
A bug from GCC 10.4 shows up in `nlohmann/json` with the new 2023.1 `icx`/`icpx` compilers during CI builds.
https://github.com/gcc-mirror/gcc/commit/423cd47cfc9640ba3d6811b780e8a0b94b704dcb
https://bugs.mageia.org/show_bug.cgi?id=30658
> Fix GitHub Action for Intel 2023.1 compilers

- .github/workflows/build-and-test-macos.yml
https://github.blog/2023-03-01-github-actions-introducing-faster-github-hosted-x64-macos-runners/
> Use `macos-latest-xl` runners for MacOS GitHub Actions jobs

- .clang-format
- .github/workflows/build-and-test-linux.yml
- .github/workflows/style.yml
Homebrew default clang is now v16.
> Updates for clang-format v16

- .github/workflows/docs.yml
Make built docs downloadable from GitHub Actions CI in PRs for 7 days.
Closes #66 
> Make built docs downloadable from CI in PRs

- .github/workflows/docs-cleanup.yml
PRs from forks do not deploy preview docs, so we get CI workflow failures like https://github.com/awslabs/palace/actions/runs/5593909532. This should resolve the issue.
> Fix Documenter cleanup GitHub Action when preview docs are not built

- .gitignore
This PR adds the documentation-generated `Manifest.toml` to the gitignore.
Closes #73
> Add `Manifest.toml` to `.gitignore`

- palace/utils/iodata.cpp
- palace/utils/iodata.hpp
For configuration files with large lists of boundary or domain attributes (for example, some 20k entries in one case), the range expansion step of configuration file parsing encounters a segmentation fault. This only shows up with GCC (not Clang) and appears to be a C++ STL bug. See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66456 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61582 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86164.
This PR rewrites this step of the parser to avoid use of `std::regex` instead.
> Fix configuration file parsing for obscure `std::regex` bug

- palace/drivers/transientsolver.cpp
- palace/fem/multigrid.hpp
- palace/linalg/ksp.cpp
- palace/linalg/strumpack.cpp
- palace/main.cpp
- palace/models/lumpedportoperator.cpp
- palace/models/surfacecurrentoperator.cpp
- palace/models/timeoperator.cpp
- palace/utils/configfile.cpp
- palace/utils/configfile.hpp
Previously every enum defined in `configfile.hpp` had a `*_INVALID` option because the behavior of the `NLOHMANN_JSON_SERIALIZE_ENUM` macro's `from_json` was to assign to the first enum in the list if no matching value was found in the provided map. This PR writes adds a custom `from_json` function which throws an error in this case, since this was always what we wanted to do, and allows us to remove these extraneous `*_INVALID` enum options from the code.
> Improve enum parsing from JSON

- docs/src/config/model.md
- palace/utils/configfile.cpp
- palace/utils/configfile.hpp
- palace/utils/geodata.cpp
- scripts/schema/config/model.json
For debugging purposes, it can be useful to strip the nodes associated high-order curved meshes and deal with only the underlying straight-sided mesh defined by the element vertices. This PR adds a `RemoveCurvature` option to the configuration file which performs this operation after loading the mesh from disk.
> Add option to remove high-order mesh curvature information

- .github/workflows/build-and-test-linux.yml
- .gitlab-ci.yml
Update to AOCL 4.1: https://www.amd.com/en/developer/aocl.html
> Updates to fix AMD AOCL CI builds

- palace/fem/lumpedelement.hpp
- palace/utils/geodata.cpp
- palace/utils/geodata.hpp
This PR fixes an issue where non-planar lumped ports were being errored out incorrectly. The fix involves fixing the bounding box calculation to better handle non-planar two dimensional objects embedded in three dimensional space, and only performing the quadrilateral area check against the integrated area if a planar port is discovered. An extra "GetProjectedLength" helper function is also included, at present it is only used in a debug assertion.
https://github.com/awslabs/palace/issues/89
> Fix for non-planar lumped ports

- .github/workflows/build-and-test-linux.yml
- .github/workflows/build-and-test-macos.yml
Added as a step for Linux and MacOS builds, before regression tests are run for the `examples/`.
> Add GitHub Actions workflow for unit tests

- palace/utils/meshio.cpp
Fix check for vertex coordinate dimension when using COMSOL mesh formats. Resolves https://github.com/awslabs/palace/issues/102.
> Fix parsing of 2D COMSOL meshes

- palace/fem/coefficient.hpp
- palace/models/waveportoperator.cpp
An `mfem::ElementTransformation` is configured at the given integration point in the loop over quadrature points inside of the element, at the level of a `Linear/BilinearForm` assembly or `GridFunction` evaluation. Calling `SetIntPoint` again will reset the transformation and require redundant computation of the element Jacobian in cases where it could have been reused.
> Remove some unneeded `SetIntPoint` calls for `Coefficient` evaluation

- palace/linalg/slepc.cpp
Most of the time this just adds confusion since PETSc is catching signals which originate somewhere else (PETSc and SLEPc are only used for the eigenvalue solve).
> Disable PETSc signal handling

- palace/drivers/basesolver.cpp
- test/examples/runtests.jl
- test/examples/testcase.jl
Previously the floating point precision of the first column of all postprocessed data outputs was set to 6. I'm increasing it to 9 to match that of all other columns and to prevent unnecessary rounding (e.g. of frequency vectors for driven solves).
*Issue #, if available:* https://github.com/awslabs/palace/issues/112
> Increase fp precision of first column of postpro files

- palace/main.cpp
Minor fix to distinguish from an OpenMP build running with 1 thread.
> Correct log printing when Palace is built without OpenMP

- docs/src/config/solver.md
- palace/linalg/divfree.cpp
- palace/linalg/errorestimator.cpp
- palace/linalg/hcurl.cpp
- palace/utils/configfile.hpp
- palace/utils/iodata.cpp
Set default smoother order for multigrid based on the solver order, and increase smooth order for mass-matrix solve in error estimation.
> Default order for Chebyshev polynomial smoothing

- .clang-format
- palace/fem/coefficient.hpp
- palace/fem/libceed/operator.cpp
- palace/fem/libceed/restriction.cpp
- palace/linalg/arpack.cpp
- palace/utils/diagnostic.hpp
- palace/utils/geodata.cpp
*Description of changes: add <numeric> header to resolve the MSVC building error
EDIT: Includes https://github.com/awslabs/palace/pull/134 and https://github.com/awslabs/palace/pull/135 as well.
*Issue #, if available:* MS Visual Studio 2022 complains. needed for std::partial_sum and std::accumulate
> Add <numeric> header to resolve the MSVC building error

- docs/src/guide/postprocessing.md
- palace/drivers/basesolver.cpp
Change the AMR generated postprocessing subdirectory from `adaptX` to `iterationX` where `X` denotes the iteration number starting from 1 on the initial mesh. Additionally update the postprocessing section of the documentation to mention this directory.
> Change postprocessing AMR subdirectory and update docs

- scripts/schema/config/solver.json
If using `MGMaxLevels` the json validator would fail because `int` isn't the same as `integer`. Tested fix using a config with `"MGMaxLevels": 1`.
> Fix json schema int bug

- palace/drivers/drivensolver.cpp
- palace/drivers/eigensolver.cpp
- palace/drivers/electrostaticsolver.cpp
- palace/drivers/magnetostaticsolver.cpp
- palace/drivers/transientsolver.cpp
- palace/linalg/errorestimator.cpp
- palace/linalg/errorestimator.hpp
Remove need to assemble multigrid hierarchy for error estimation solve.
Missed from #143.
> Multigrid cleanup from error estimation

- scripts/palace
Previously, even if the binary exited with non-zero exit code the wrapper script would still return 0.
> Return exit code from Palace in wrapper script

- palace/linalg/divfree.hpp
- palace/linalg/gmg.cpp
- palace/linalg/gmg.hpp
- palace/linalg/iterative.cpp
- palace/linalg/iterative.hpp
- palace/linalg/ksp.cpp
- palace/utils/timer.hpp
Configure linear solver timing to only count preconditioning and coarse solve time for primary solvers (not error estimation, divergence-free projection, etc.). Also add timing category for divergence-free projection for eigenvalue solves.
> Timer fixes for linear solves

- docs/src/config/solver.md
- palace/utils/configfile.cpp
- palace/utils/configfile.hpp
- palace/utils/geodata.cpp
- scripts/schema/config/solver.json
Add option to disable mesh refinement levels from MG hierarchy: `"MGUseMesh"` (default is true).
> Config file option for disabling h-multigrid

- palace/drivers/basesolver.cpp
- palace/models/timeoperator.cpp
- palace/utils/iodata.cpp
- Do not print AMR warning for transient simulations without AMR enabled
- Add absolute tolerance for transient linear solve to silence warnings when RHS vector is zero
- Fix a comment
> Minor warning fixes

- palace/models/postoperator.cpp
- palace/models/postoperator.hpp
- palace/utils/geodata.cpp
This results from https://github.com/awslabs/palace/pull/128, where we are rescaling the mesh nodes before writing the VTU output for ParaView visualization. For parallel simulations, the neighbor mesh nodes also need to be scaled so that evaluation using the neighbor `ElementTransformation` objects works.
Also from that PR, this fixes the output of fields with non-identity Piola transformations from the reference to physical space evaluations. H(curl) fields transform with `J^{-T}` and thus need scaling with L when the mesh nodes are scaled by L. Likewise H(div) transform with `J / |J|` and thus need scaling with `L^{d-1}`.
Resolves https://github.com/awslabs/palace/issues/156
> Fix bug with mesh nondimensionalization for parallel meshes

- cmake/ExternalMFEM.cmake
- extern/patch/mfem/patch_pncmesh_update_fix.diff
Proposed changes to `sjg/geodata-updates` to patch the issue with `"SaveAdaptMesh": true` causing segfaults. Tested on the cavity example with
```
"Refinement":
{
"MaxIts": 2,
"SaveAdaptMesh": true
}
```
> Patch for ParNCMesh::Update bug

- cmake/ExternalMFEM.cmake
- extern/patch/mfem/patch_pncmesh_update_fix.diff
- palace/drivers/basesolver.cpp
- palace/models/lumpedportoperator.cpp
- palace/models/lumpedportoperator.hpp
- palace/models/surfaceconductivityoperator.cpp
- palace/models/surfaceconductivityoperator.hpp
- palace/models/surfacecurrentoperator.cpp
- palace/models/surfacecurrentoperator.hpp
- palace/models/surfaceimpedanceoperator.cpp
- palace/models/surfaceimpedanceoperator.hpp
- palace/models/waveportoperator.cpp
- palace/models/waveportoperator.hpp
- palace/utils/configfile.cpp
- palace/utils/configfile.hpp
- palace/utils/geodata.cpp
- palace/utils/geodata.hpp
Minor cleanup of geodata helper functions and declarations, in preparation for `palace::Mesh` class. Includes some `const` correctness fixes for `mfem::Mesh` enabled by https://github.com/awslabs/palace/pull/151.
> Cleanup in `geodata.hpp/cpp`

- palace/models/materialoperator.cpp
https://github.com/awslabs/palace/pull/166 introduced an issue where coefficients with matching attribute lists, might have different size K, if all the attributes are `-1`. This is a consequence of [these lines](https://github.com/awslabs/palace/blob/main/palace/models/materialoperator.cpp#L696-L706) where a coefficient goes from size zero to size 1, even if there were no local attributes associated. This triggers [these lines](https://github.com/awslabs/palace/blob/main/palace/models/materialoperator.cpp#L627-L635) if `attr_mat` is all -1, but the incoming coefficient is of size zero. This can occur if one rank does not have any piece of the relevant geometry. The fix is if `attr_list` is entry in adding a coefficient, to do nothing.
> Bugfix: Coefficient for empty `attr_list`

- .github/workflows/build-and-test-linux-aarch64.yml
- .github/workflows/build-and-test-macos.yml
- .github/workflows/docs-cleanup.yml
- .github/workflows/docs.yml
- .github/workflows/singularity.yml
- .github/workflows/style.yml
Fixes the following warnings:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
> Bump GitHub actions versions for Node.js deprecation warnings

- scripts/palace
This is useful when using OpenMP and a small enough number of MPI processes that the default binding leads to `--bind-to core`. It's just a default so can always be overridden by the user with the `--launcher-args` option.
> Set default MPI launcher arguments to `--bind-to none` for threaded runs

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- .github/workflows/build-and-test-linux.yml
Also one missed version from #182
> Minor changes for GitHub issue/PR templates

- palace/fem/fespace.hpp
- palace/fem/libceed/basis.cpp
- palace/fem/libceed/ceed.cpp
- palace/fem/libceed/integrator.cpp
- palace/fem/libceed/integrator.hpp
- palace/fem/mesh.cpp
- palace/fem/qfunctions/21/geom_21_qf.h
- palace/fem/qfunctions/22/geom_22_qf.h
- palace/fem/qfunctions/32/geom_32_qf.h
- palace/fem/qfunctions/33/geom_33_qf.h
- palace/fem/qfunctions/geom_qf.h
- palace/linalg/operator.cpp
- palace/linalg/operator.hpp
- palace/linalg/rap.cpp
- palace/linalg/rap.hpp
- palace/models/curlcurloperator.cpp
- palace/models/laplaceoperator.cpp
- palace/models/spaceoperator.cpp
- Only parallelize libCEED across OpenMP threads when CPU backends are used
- Add some missing `AddMult`/`AddMultTranspose` overrides and avoid calling them when they don't exist to avoid temporary vectors
- Avoid constructing discrete gradient matrix on coarse mesh unless necessary for coarse solve (AMS)
> Collection of minor performance fixes during profiling and GPU testing

- palace/linalg/ams.cpp
- palace/utils/geodata.cpp
- palace/utils/geodata.hpp
- palace/utils/iodata.cpp
Expands use of OpenMP to a few detected hot-spots:
- AMS nodal coordinates construction
- Mesh bounding boxes and other loops in `geodata.cpp`
> Add OpenMP parallelism where possible

- docs/src/config/boundaries.md
- palace/fem/coefficient.hpp
- palace/models/lumpedportoperator.cpp
- palace/models/lumpedportoperator.hpp
- palace/models/waveportoperator.cpp
- palace/models/waveportoperator.hpp
- palace/utils/configfile.cpp
- palace/utils/configfile.hpp
- scripts/schema/config/boundaries.json
Resolves #171.
In addition, this PR changes field visualization on internal boundaries to always chose the field on the vacuum side (previously, sometimes used vacuum and sometimes used side with lower speed of light).
> Add `"Active"` config file field for lumped and wave ports

- palace/models/postoperator.cpp
We redimensionalize the mesh coordinates and the local parts of the fields, but also need to redimensionalize the face neighbor data vectors (which have already been exchanged, based on the nondimensional dof data). This resolves issues where the fields for shared faces appear to be very small or very large relative to the rest of the boundary visualization.
Note: This should not have an effect on surface integrals based on boundary coefficients for problems with internal boundaries (like integrated charge, or surface participation). These integrals are computed outside of the field nondimensionalization/redimensionalization, so this bug only affects visualization and also only for parallel simulations which boundary elements coinciding with shared faces.
> Fix ParaView output on boundary mesh for shared faces

- palace/models/materialoperator.cpp
- palace/models/materialoperator.hpp
- palace/utils/communication.hpp
Methods like `MaterialOperator::HasLossTangent` are expected to return a value which is consistent globally. This is not the case currently, as material properties are parsed only with respect to local subdomains. This PR fixes this issue and potential hangs for large processor counts or small domains of nonzero loss tangent or conductivity.
> Fix global synchronization bug for optional material properties

- CHANGELOG.md
- README.md
- docs/make.jl
- docs/src/guide/guide.md
- docs/src/guide/parallelism.md
- docs/src/guide/postprocessing.md
- docs/src/index.md
- docs/src/install.md
- examples/cavity/cavity_impedance.json
- examples/cavity/cavity_pec.json
- examples/coaxial/coaxial_matched.json
- examples/coaxial/coaxial_open.json
- examples/coaxial/coaxial_short.json
- examples/cpw/cpw_lumped_adaptive.json
- examples/cpw/cpw_lumped_uniform.json
- examples/cpw/cpw_wave_adaptive.json
- examples/cpw/cpw_wave_uniform.json
- examples/rings/rings.json
- examples/spheres/spheres.json
Accompanies #184 and resolves #3
> Documentation for GPU support

- palace/drivers/basesolver.cpp
- palace/fem/CMakeLists.txt
- palace/fem/bilinearform.cpp
- palace/fem/coefficient.hpp
- palace/fem/gridfunction.cpp
- palace/fem/gridfunction.hpp
- palace/fem/interpolator.cpp
- palace/fem/interpolator.hpp
- palace/models/domainpostoperator.cpp
- palace/models/domainpostoperator.hpp
- palace/models/lumpedportoperator.cpp
- palace/models/lumpedportoperator.hpp
- palace/models/postoperator.cpp
- palace/models/postoperator.hpp
- palace/models/surfacepostoperator.cpp
- palace/models/surfacepostoperator.hpp
- palace/models/waveportoperator.cpp
- palace/models/waveportoperator.hpp
We have observed some issues with `mfem::Memory` aliasing when running on GPUs, which look like error messages of the form:
```
CUDA error: (cudaMemcpy(dst, src, bytes, cudaMemcpyHostToDevice)) failed with error:
--> misaligned address
... in function: void* mfem::CuMemcpyHtoD(void*, const void*, size_t)
... in file: /data/home/hughcars/palace/build_g5_48xlarge/extern/mfem/general/cuda.cpp:116
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.
NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
``` …
> Add `palace::GridFunction` to unify `mfem::ParGridFunction` and `mfem::ParComplexGridFunction`

- examples/cpw/mesh/mesh.jl
- palace/drivers/basesolver.cpp
- palace/utils/geodata.cpp
- palace/utils/geodata.hpp
This is enabled by the addition of conformal rebalancing for AMR. The mesh can get quite imbalanced following a few levels of local refinement and rebalancing speeds up the following simulations significantly.
> Rebalance mesh after region-based refinement

- CHANGELOG.md
- palace/drivers/eigensolver.cpp
- palace/drivers/electrostaticsolver.cpp
- palace/drivers/magnetostaticsolver.cpp
- palace/models/curlcurloperator.cpp
- palace/models/domainpostoperator.cpp
- palace/models/domainpostoperator.hpp
- palace/models/laplaceoperator.cpp
- palace/models/postoperator.cpp
- palace/models/spaceoperator.cpp
Use the scalar voltage (H1) and vector potential (Nedelec) fields, which typically have smaller space dimension than the corresponding electric field (Nedelec) and magnetic flux density (Raviart-Thomas).
This can actually become a bottleneck for large capacitance or inductance matrix sizes, where `O(N^2)`, with `N` the number of terminals, energy calculations are needed.
> Improve field energy integration for electrostatic and magnetostatic simulations

- palace/drivers/basesolver.cpp
AMR users often want to know how long a simulation takes not only for the whole, but also for each iteration. This is particularly helpful when running AMR simulations that might terminate due to running out of memory etc. where the final timing data will not be reported. This PR adds timing printing to the log, and recording of the meta data file, to each AMR loop in addition to the final print.
> Record timing for each stage of AMR

- palace/utils/iodata.cpp
- palace/utils/prettyprint.hpp
- scripts/schema/config/boundaries.json
- scripts/schema/config/domains.json
Previously, an (incorrect) configuration file array specified as `"Attributes": []` would lead to an error like:
```
Verification failed: (ec == std::errc()) is false:
--> Invalid integer conversion in range expansion!
... in function: palace::{anonymous}::PreprocessFile(const char*)::<lambda(std::string_view)>
... in file: /apps/palace/palace/palace/utils/iodata.cpp:77
```
This case is now handled and checked for in the JSON Schema during `--dry-run`.
> Fix cryptic error for empty arrays in JSON config file

- palace/linalg/ams.cpp
- palace/linalg/hypre.cpp
- palace/linalg/hypre.hpp
Add owning and non owning constructors for `HypreCSRMatrix` from `mfem::SparseMatrix`.
https://github.com/awslabs/palace/issues/216
> Add owning and non constructors from mfem::SparseMatrix

- docs/src/config/solver.md
- palace/drivers/drivensolver.cpp
- palace/drivers/eigensolver.cpp
- palace/drivers/electrostaticsolver.cpp
- palace/drivers/electrostaticsolver.hpp
- palace/drivers/magnetostaticsolver.cpp
- palace/drivers/magnetostaticsolver.hpp
- palace/drivers/transientsolver.cpp
- palace/linalg/amg.cpp
- palace/linalg/chebyshev.cpp
- palace/linalg/chebyshev.hpp
- palace/linalg/distrelaxation.hpp
- palace/linalg/divfree.cpp
- palace/linalg/errorestimator.cpp
- palace/linalg/errorestimator.hpp
- palace/linalg/iterative.cpp
- palace/linalg/jacobi.cpp
- palace/linalg/jacobi.hpp
- palace/linalg/ksp.cpp
- palace/linalg/solver.hpp
- palace/models/curlcurloperator.cpp
- palace/models/laplaceoperator.cpp
- palace/models/laplaceoperator.hpp
- palace/models/postoperator.cpp
- palace/models/postoperator.hpp
- palace/models/spaceoperator.cpp
- palace/models/timeoperator.cpp
- palace/utils/configfile.cpp
- palace/utils/configfile.hpp
- scripts/schema/config/solver.json
For electrostatic problems, PR https://github.com/awslabs/palace/pull/209 made the change from a global vector H1 project to a global RT-space projection, which increased the time spent in the linear solve by a factor of 5 or more. This PR is the result of some experimentation with how to speed up the linear solve associated with error estimation.
The current default is still to use Jacobi-preconditioned CG, but now a runtime option can switch this back to AMG (with matrix-free p-MG when order > 1) for problems where the increased memory overhead is worth the improved convergence rate.
> Add `"EstimatorMG"` option for estimation mass matrix linear solve

- CHANGELOG.md
- palace/models/lumpedportoperator.cpp
- palace/models/lumpedportoperator.hpp
- palace/models/postoperator.cpp
- palace/models/postoperator.hpp
- palace/models/surfacepostoperator.cpp
Resolves https://github.com/awslabs/palace/issues/222.
> Fix current postprocessing for lumped ports

- palace/utils/timer.hpp
Fix after https://github.com/awslabs/palace/pull/212. The total time value for AMR simulations, when reduction is performed more than once, was previously double counting and printing an incorrect value.
> Fix timer value of `Timer::TOTAL` for AMR simulations

- scripts/palace
Resolves https://github.com/awslabs/palace/issues/228.
> Fix executable script wrapper for Slurm jobs

- palace/models/curlcurloperator.cpp
- palace/models/farfieldboundaryoperator.cpp
- palace/models/laplaceoperator.cpp
- palace/models/spaceoperator.cpp
- palace/models/surfacepostoperator.cpp
- palace/utils/geodata.cpp
- palace/utils/geodata.hpp
Farfield/absorbing boundary conditions and boundary postprocessing can just warn and and ignore invalid boundary attributes. This doesn't pose too much of a risk for users and warnings are sufficiently visible in the log file. This is a usability improvement when copy-pasting large numbers of boundary attributes for models when some domains may not be meshed or may be removed due to no material properties being specified.
> Relax requirements for invalid boundary attributes specified for certain boundary conditions

- .github/workflows/build-and-test-linux-aarch64.yml
See https://github.com/uraimo/run-on-arch-action?tab=readme-ov-file#usage
40m 46s -> 3h 37m 22s (after Docker updated `ubuntu:latest` to 24.04 with Clang 18, https://github.com/awslabs/palace/pull/239) -> 39m 54s (this PR, after switch to GCC 13)
> Speed up run-on-arch action

- palace/drivers/basesolver.cpp
- palace/drivers/electrostaticsolver.cpp
- palace/drivers/electrostaticsolver.hpp
- palace/drivers/magnetostaticsolver.cpp
- palace/drivers/magnetostaticsolver.hpp
- palace/models/domainpostoperator.hpp
- palace/models/postoperator.hpp
- palace/models/surfacepostoperator.hpp
Reduces the number of matrix-vector products by `N*(N-1)/2` for `N` terminals or current sources. Still requires `N*(N+1)/2` dot products.
Note: Based on https://github.com/awslabs/palace/pull/234
> Optimize electrostatic and magnetostatic capacitance matrix postprocessing

- CHANGELOG.md
- palace/fem/lumpedelement.cpp
- palace/fem/lumpedelement.hpp
- palace/utils/geodata.cpp
- palace/utils/geodata.hpp
Previously, for coaxial lumped ports with particularly coarse meshes, the following assertion would fail in `geodata.cpp`'s `BoundingBallFromPointCloud`:
```
MFEM_VERIFY(std::abs(PerpendicularDistance({delta}, perp) - ball.radius) <=
rel_tol * ball.radius,
"Furthest point perpendicular must be on the exterior of the ball: "
<< PerpendicularDistance({delta}, perp) << " vs. " << ball.radius
<< "!");
```
This PR improves the bounding ball algorithm to avoid this error (and is a simpler algorithm). We now just compute the ball origin as the average of all points and radial direction as the point furthest from the centroid. The rest of the algorithm is unchanged.
Here is an example second-order mesh which was causing problems prior to this PR:
> Fix bounding ball calculation for coaxial lumped ports

- palace/models/curlcurloperator.cpp
- palace/models/farfieldboundaryoperator.cpp
- palace/models/laplaceoperator.cpp
- palace/models/spaceoperator.cpp
- palace/models/surfaceconductivityoperator.cpp
- palace/models/surfaceimpedanceoperator.cpp
- palace/models/surfacepostoperator.cpp
- palace/models/surfacepostoperator.hpp
- palace/utils/communication.hpp
- palace/utils/geodata.cpp
- palace/utils/prettyprint.hpp
- Add surface impedance and surface conductivity BCs to allow invalid attributes, following https://github.com/awslabs/palace/pull/224.
- Fix invalid BC warning messages to be more concise.
- Update `Mpi::Warning` color to highlight warnings and increase column width for `PrettyPrint` to 80 characters from 60.
Note: Based on https://github.com/awslabs/palace/pull/242
> Revisiting boundary condition warning messages from #224

- palace/utils/meshio.cpp
Updating `clang-format` v18 minor versions seems to have introduced a needed style fix.
> Style fix with updated clang-format for CI

- CHANGELOG.md
- cmake/ExternalMFEM.cmake
- extern/patch/mfem/patch_nc_internal_project.diff
This PR introduces a patch to mfem for nc internal boundaries, where for electrostatics internal boundary conditions would fail to project onto NC refined faces where face dof were present (p > 3). The patch is addressed against mfem at https://github.com/mfem/mfem/pull/4259.
Before:
After:
> Add patch for projection onto NC internal boundaries

- CHANGELOG.md
- palace/fem/coefficient.hpp
As part of https://github.com/awslabs/palace/pull/240, using `"Side": "LargerRefractiveIndex"` was not handled correctly. This caused regressions for some meshes with internal boundaries, but was not caught by the CI tests because the meshes for the CPW test which should have tested this were a special case that happened to still give the correct result.
> Bug fix for boundary postprocessing from #240

- .github/workflows/build-and-test-linux.yml
- .github/workflows/build-and-test-macos.yml
- cmake/ExternalLIBXSMM.cmake
See https://github.com/libxsmm/libxsmm/issues/883. Until this is fixed, just build directly into installation location and manually install pkg-config files and headers.
> Fix LIBXSMM installation

- CHANGELOG.md
- docs/src/config/boundaries.md
- docs/src/config/solver.md
- palace/drivers/eigensolver.cpp
- palace/models/waveportoperator.cpp
- palace/models/waveportoperator.hpp
- palace/utils/configfile.cpp
- palace/utils/configfile.hpp
- palace/utils/iodata.cpp
- scripts/schema/config/boundaries.json
Wave port mode calculation right now inherits all PEC boundary conditions from the 3D problem. Conductivity boundaries should also be considered as PEC for mode calculation (otherwise it was expected the user adds them with `"WavePortPEC"`).
Also updates the eigenvalue target for the shifted wave port eigemode problem to `EigenvalueSolver::WhichType::SMALLEST_REAL`, which appropriately deprioritizes evanescent modes with large imaginary part and small real part of `k_n`.
> Add conductivity boundaries to Dirichlet BC list for wave ports

- CHANGELOG.md
- palace/linalg/divfree.cpp
- palace/linalg/divfree.hpp
This avoids solving a singular Laplace problem when calculating the scalar potential for a model with no real boundaries. For example, this can be observed by printing the output of divergence-free projection linear solve for the cavity example with PMC boundaries. After this PR, the divergence-free solves actually converge normally in a few iterations and the eigensolve converges as well.
Correctly handles the case of some subdomains having potentially no true dofs and just enforces a potential = 0 on the processor of lowest rank with some non-zero number of local true dofs.
> Fix divergence cleaning when a model has no real boundaries

- docs/src/guide/boundaries.md
- palace/fem/lumpedelement.cpp
- palace/utils/geodata.cpp
- palace/utils/geodata.hpp
Very minor perturbations to a perfect quadrilateral or rectangular prism caused the entire algorithm to fail and led to failed `MFEM_VERIFY` statements for the direction in `UniformElementData`'s constructor.
> Fix oriented bounding box calculation for lumped ports, in preparation for #261

- cmake/ExternalGitTags.cmake
- extern/patch/mfem/patch_gmsh_parser_performance.diff
- extern/patch/mfem/patch_mesh_prism_vtu_fix.diff
- extern/patch/mfem/patch_mesh_vis_dev.diff
- extern/patch/mfem/patch_par_tet_mesh_fix_dev.diff
- extern/patch/mumps/patch_build.diff
* Update dependency git tags
* Rebuild mumps build patch
* Rebuild mfem patch sequence
> Update dependencies and patches

- palace/utils/geodata.cpp
Fix a bug where boundary elements would always be cracked.
> Crack elements only when requested

- .github/workflows/style.yml
- examples/cpw/cpw.jl
- examples/cpw/mesh/mesh.jl
- examples/cylinder/cavity.jl
- examples/cylinder/mesh/mesh.jl
- examples/rings/mesh/mesh.jl
- palace/fem/errorindicator.cpp
- palace/utils/geodata.cpp
Update clang format to match the version vended by homebrew.
> Update clang-format to 19

- .github/workflows/build-and-test-linux.yml
- .github/workflows/spack.yml
There is an internal compiler error in 2025.0 for the fortran compiler. This prevents STRUMPACK from building in CI, see https://github.com/awslabs/palace/pull/293. This change fixes the version to the previously work 2024.2.1 until a patch for 2025 is released.
Future removal of this rollback is documented in https://github.com/awslabs/palace/issues/295.
> Fix intel oneapi versions to 2024.2.1

- .github/workflows/build-and-test-macos.yml
- cmake/ExternalBLASLAPACK.cmake
- cmake/ExternalHYPRE.cmake
In some macos github action builds:
```
[build-and-test-macos (gcc, openmpi, openblas, static, int64, openmp, superlu, arpack)](https://github.com/awslabs/palace/actions/runs/11825573260/job/32994205616#step:4:17)
You are using macOS 12.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a …
```
> Update Github actions

- .github/workflows/build-and-test-macos.yml
Mac OS CI failing due to pkg config not updating on the new runners. See https://github.com/awslabs/palace/actions/runs/11977558035/job/33395703593?pr=272
> Force link of pkgconf to new version on mac OS runners

- examples/rings/mesh/mesh.jl
The default arguments in `rings/mesh.jl` were not being used. Additionally the default value for `rot_θ` did not match the value used in the configuration file.
> Fix arg error in rings/mesh.jl

- spack/local/packages/palace/package.py
Split depends_on commands to remove `^` usage.
This fixes errors such as:
```
==> Added repo with namespace 'local'.
==> Error: cannot load package 'palace' from the 'local' repository: the '^' sigil cannot be used in 'depends_on' directives. Please reformulate the directive below as multiple directives:
depends_on("slepc+cuda cuda_arch=10 ^petsc+cuda cuda_arch=10", when="+cuda+slepc cuda_arch=10")
Error: Process completed with exit code 1.
```
> Fix spack build issue when using ^ in depends_on

- CHANGELOG.md
- docs/src/config/solver.md
- palace/drivers/eigensolver.cpp
- palace/models/spaceoperator.cpp
The London equation implementation has an issue where the london depth is added as a curlcurl term, where it should have been added as a mass term. This was due to a typo where `df` was used instead of `f`. The effect of the London equation is to make a reaction-diffusion (second order) boundary layer in the London region, which is independent of driving frequency, hence needing the mass term. The magnetic boundary layer effect was confirmed after this fix.
Additionally to get good results requires disabling the divergence free cleaner, as the mass term results in a change to the nullspace of the stiffness matrix.
> London Equation bugfix

- palace/utils/geodata.cpp
When encountering the multiple boundary element error, report the attributes of the elements to help users fix the issue in their mesh.
> Report boundary attributes in error message

- docs/src/config/model.md
- palace/utils/configfile.cpp
- palace/utils/configfile.hpp
- palace/utils/geodata.cpp
- scripts/schema/config/model.json
Palace does some pre-processing of the mesh to enable mesh cracking. To enable comparative studies on the same mesh whether mesh cracking is used or not, users may want an option to export this mesh after pre-processing, before cracking, for use with other configurations.
> Export mesh after cracking pre-processing

- CHANGELOG.md
- palace/drivers/drivensolver.cpp
- palace/drivers/eigensolver.cpp
- palace/drivers/electrostaticsolver.cpp
- palace/drivers/magnetostaticsolver.cpp
- palace/drivers/transientsolver.cpp
- palace/models/postoperator.cpp
- palace/models/postoperator.hpp
- palace/models/postoperatorcsv.cpp
- palace/models/postoperatorcsv.hpp
- palace/utils/CMakeLists.txt
- palace/utils/iodata.cpp
- palace/utils/tablecsv.cpp
- palace/utils/tablecsv.hpp
Suggested fixes for `phdum/new_postpro` in https://github.com/awslabs/palace/pull/302
> PR feedback for phdum/new_postpro

- palace/utils/meshio.cpp
Revert change that introduced bug with extra arguments on `compare`:
```
Verification failed: (skip_type || num_elem_nodes == ElemNumNodes[elem_type - 1]) is false:
--> Mismatch between COMSOL and Gmsh element types!
... in function: void palace::mesh::ConvertMeshComsol(const std::string&, std::ostream&, bool)
... in file: /data/home/hughcars/palace/palace/utils/meshio.cpp:851
```
when loading a comsol mesh.
> Fix bug for comsol mesh element reading

- palace/utils/iodata.cpp
Higher order far-field boundary conditions are only supported in driven system, since like wave-ports they have a non LRC frequency dependance. Technically, this is enforced when building the matrices here:
https://github.com/awslabs/palace/blob/78043460e7dca7fcf0b57349477da69a8771cde6/palace/models/farfieldboundaryoperator.cpp#L83
It would be nice to enforce this along with all similar conditions in the config options. (e.g. we enforce no farfield be for the DC simulations in config).
PR is trivial, but would be nice for a second pair of eyes to double check logic / bool condition is correct.
> Add missing error for unsupported set-up configurations early

- palace/models/postoperator.cpp
Fixes a small typo causing the absolute and backward eigenvalue errors to get printed under the wrong column headers.
> Fix eigenvalue errors printed in wrong columns

- .github/workflows/spack.yml
In #394 and #397, @hughcars observed that the Spack pipelines are failing due to the inability for external fork based PRs to push to the GHCR cache.
This PR attempts to resolve that issue.
> Move binary cache push to end of Spack pipeline

- cmake/ExternalGitTags.cmake
Scalapack does not build with gcc15 after they changed the default c language standard, (see https://github.com/Reference-ScaLAPACK/scalapack/issues/129). This patch addresses the misspecified function declarations by adding in arguments. 
Upstream scalapack PR: https://github.com/Reference-ScaLAPACK/scalapack/pull/139
> Patch for scalapack to build with gcc-15

- .github/workflows/build-and-test-linux.yml
- .github/workflows/build-and-test-macos.yml
- .github/workflows/singularity.yml
- .github/workflows/spack.yml
This PR optimizes CI resource usage by adding paths-ignore filters to skip expensive build and test workflows when only Markdown files are modified.
This only applies to pull requests, and not to the push to main (so that we can ensure that every test is always green for every commit on main)
> Skip expensive CI actions when only modifying Markdowns

- palace/drivers/eigensolver.cpp
Fixes compiler warning:
```
320 |     double mean_phase = linalg::NormalizePhase(space_op.GetComm(), E);
|            ^~~~~~~~~~
1 warning generated.
```
> Remove assignment to `mean_phase`

- palace/utils/geodata.cpp
The `ComputeNormal` method checks against `last_normal` despite it being uninitialized. This PR zero initializes and fixes the verification.
> Fix uninitialized last_normal

- .github/workflows/build-and-test-macos.yml
The default macos image updated, breaking the runners. This updates to using llvm18 and gcc14 which are on the osx15 image, from the old 15 and 12.
> Update clang to 18 and gcc to 15 inlight of update macos runners

- .github/workflows/docs.yml
- docs/Project.toml
- docs/make.jl
- docs/src/install.md
- docs/src/quick.md
- examples/spheres/mesh/mesh.jl
- examples/spheres/spheres.json
This PR adds a "Quick Start" tutorial that walks new users through their first simulation by providing a different view on the "two sphere" example. 
The aim of the tutorial is to expose new users to the basic concepts involved with installing palace and running and analyzing simulations. `quick.md` leverages Documenter.jl's ability to execute code upon doc generation, so that many sections in the tutorial are populated automatically. This has two consequences:
- the "quick start" experience itself is somewhat tested,
- many updates to the two sphere examples or to palace are automatically reflected to the rendered tutorial.
For this to happen, I updated the docs.yml to install palace with spack. In order to avoid a 30+ minute build, the workflow has to be configured to ensure that it …
> Add "Quick Start" tutorial

- .github/workflows/spack.yml
- spack_repo/local/packages/palace/package.py
I found that when building with all variants enabled for Palace, I get an error in Spack builds:
```
==> Installing palace-develop-fs4n7434ld4psa3gabzs3wc3ch26ikrh [39/39]
...
20    -- Detecting Fortran compiler ABI info
21    -- Detecting Fortran compiler ABI info - failed
22    -- Check for working Fortran compiler: /data/home/lgh/projects/hpc-toolkit-examples/external-s
pack-root/opt/spack/linux-x86_64_v3/compiler-wrapper-1.0-ntccuj2fi3y7asqifeq3i4iylrbxakw2/libe
xec/spack/gcc/gfortran
23    -- Check for working Fortran compiler: /data/home/lgh/projects/hpc-toolkit-examples/external-s
pack-root/opt/spack/linux-x86_64_v3/compiler-wrapper-1.0-ntccuj2fi3y7asqifeq3i4iylrbxakw2/libe
xec/spack/gcc/gfortran - broken
>> 24    CMake Error at …
```
> Add fortran dep when building with fortran based deps.

- palace/drivers/drivensolver.cpp
- palace/drivers/eigensolver.cpp
- palace/linalg/errorestimator.cpp
- palace/linalg/rap.cpp
- palace/linalg/rap.hpp
- palace/linalg/vector.hpp
- palace/models/romoperator.cpp
- palace/models/spaceoperator.cpp
- palace/models/spaceoperator.hpp
- palace/utils/configfile.cpp
- palace/utils/configfile.hpp
- palace/utils/iodata.hpp
- test/unit/CMakeLists.txt
- test/unit/test-geodata.cpp
- test/unit/test-rap.cpp
The nonlinear eigenvalue problem PR can be simplified if the `BuildParSumOperator` capability wasn't tied into `SpaceOperator`, this PR refactors to expose it. Plucks a commit from @simlapointe's branch to support complex coefficients and then fixes a typo.
> Refactor BuildParSumOperator for wider usage

- docs/src/developer/tutorial_add_new_unit_test.md
- test/unit/test-config.cpp
- test/unit/test-geodata.cpp
- test/unit/test-postoperator.cpp
- test/unit/test-postoperatorcsv.cpp
- test/unit/test-rap.cpp
- test/unit/test-vector.cpp
This change removes usage of deprecated `Catch2::Approx` in favor of the more explicit `WithinAbs`/`WithinRel` matchers. 
Closes #486.
> Replace deprecated Catch2::Approx with Catch2::Matchers

- docs/src/config/boundaries.md
- docs/src/guide/boundaries.md
Update the wave port documentation to clarify how boundary conditions from the full 3D model are mapped to PEC and PMC in the 2D wave port eigenproblem. Also update a few places in the docs stating that frequency-dependent boundary conditions are only available for driven simulations (they are now available for both driven and eigenmode).
> Update wave port documentation
