palace/drivers/drivensolver.cpp
palace/drivers/eigensolver.cpp
palace/drivers/electrostaticsolver.cpp
palace/drivers/magnetostaticsolver.cpp
palace/fem/curlcurloperator.cpp
palace/fem/curlcurloperator.hpp
palace/fem/laplaceoperator.cpp
palace/fem/laplaceoperator.hpp
palace/fem/romoperator.cpp
palace/fem/spaceoperator.cpp
palace/fem/spaceoperator.hpp
palace/fem/timeoperator.cpp
palace/linalg/curlcurl.cpp
palace/linalg/divfree.cpp
palace/linalg/feast.cpp

Use changes from https://github.com/mfem/mfem/pull/3056.

Clean up Dirichlet BC elimination

---

.github/workflows/build-and-test-linux-aarch64.yml
.github/workflows/build-and-test-linux.yml
.github/workflows/build-and-test-macos.yml
.github/workflows/spack.yml
.github/workflows/style.yml

Also, add a CI job to test Spack builds.

Run GitHub Actions for PRs from forks

---

docs/src/config/boundaries.md

Revise the Conductivity BC variable type from int to float.
N/A, found it when I read the doc.

Revise Conductivity variable from int to float

---

CHANGELOG.md
CMakeLists.txt
docs/make.jl
docs/src/config/boundaries.md
docs/src/guide/boundaries.md
docs/src/guide/guide.md
docs/src/guide/model.md
docs/src/guide/problem.md
palace/CMakeLists.txt
palace/linalg/chebyshev.cpp
palace/utils/geodata.cpp
scripts/schema/config/boundaries.json

Final changes for Palace version 0.11.1 (minor bug fix release).

Release v0.11.1

---

palace/utils/geodata.cpp

A small fix for the original bug fix in commit c313f819.
~~NOTE: Currently based on #44, so review only b343e6c and rebase once #44 is approved and merged.~~

Fix bug introduced in c313f81 for mesh preprocessing

---

CHANGELOG.md
CMakeLists.txt
Makefile
palace/CMakeLists.txt
palace/cmake/PkgConfigHelpers.cmake
scripts/format-source

Final changes for Palace version 0.11.2 (minor release mainly for Spack builds).

Release v0.11.2

---

spack/local/packages/palace/package.py

See https://github.com/spack/spack/pull/38910.

Spack recipe updates

---

.github/workflows/style.yml
scripts/format-source
scripts/schema/config/boundaries.json
scripts/validate-config

If Julia code fails inside of a Bash script, make sure an exit code is returned.

Fix Julia exit codes for scripts

---

docs/src/reference.md

Fix minor typos in reference.md I found while reading.

Fix typos in reference.md

---

extern/patch/mfem/patch_par_tet_mesh_fix.diff

Fix conditional on uninitialized value issue caught in `valgrind`.

Small fix to MFEM parallel mesh patch

---

palace/CMakeLists.txt
palace/cmake/StaticAnalysisHelpers.cmake
palace/drivers/CMakeLists.txt
palace/fem/CMakeLists.txt
palace/linalg/CMakeLists.txt
palace/models/CMakeLists.txt
palace/utils/CMakeLists.txt
test/unit/CMakeLists.txt

Link the executable (main.cpp) against it to reuse the build for tests.

Add library target libpalace.a/.so

---

.github/workflows/build-and-test-linux-aarch64.yml
.github/workflows/build-and-test-linux.yml
.github/workflows/build-and-test-macos.yml
.github/workflows/spack.yml
palace/main.cpp

This is a small change to fix the building hiccup when GPU is enabled.
A minor building error.

Fix a build issue when MFEM_USE_CUDA or MFEM_USE_HIP enabled

---

palace/drivers/basesolver.cpp
palace/fem/libceed/operator.cpp
palace/fem/multigrid.hpp
palace/linalg/gmg.hpp
palace/linalg/operator.cpp
palace/linalg/operator.hpp
scripts/format-source

Also two small bug fixes:
- Fix if zero MG levels are specified
- Fix minor uninitialized variable caught with ASan

Minor formatting and bug fixes

---

CHANGELOG.md
README.md
docs/src/config/boundaries.md
docs/src/config/model.md
docs/src/config/solver.md
docs/src/developer.md
docs/src/examples/cavity.md
docs/src/examples/coaxial.md
docs/src/examples/cpw.md
docs/src/examples/rings.md
docs/src/examples/spheres.md
docs/src/guide/boundaries.md
docs/src/guide/model.md
docs/src/guide/postprocessing.md
docs/src/guide/problem.md
docs/src/index.md
docs/src/install.md
docs/src/reference.md
docs/src/run.md

Address assorted documentation issues.
https://github.com/awslabs/palace/issues/145

Assorted documentation fixes

---

CHANGELOG.md

These were incorrectly deleted in https://github.com/awslabs/palace/pull/146/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed.

Fix missing v0.12 changelog updates

---

palace/main.cpp
palace/models/lumpedportoperator.cpp
palace/utils/configfile.hpp

Minor fixes following #166

---

CHANGELOG.md
palace/drivers/basesolver.cpp
palace/drivers/drivensolver.cpp
palace/drivers/eigensolver.cpp
palace/drivers/electrostaticsolver.cpp
palace/drivers/magnetostaticsolver.cpp
palace/drivers/transientsolver.cpp
palace/linalg/divfree.cpp
palace/linalg/divfree.hpp
palace/linalg/errorestimator.cpp
palace/linalg/gmg.cpp
palace/linalg/gmg.hpp
palace/linalg/iterative.cpp
palace/linalg/ksp.cpp
palace/linalg/ksp.hpp
palace/models/materialoperator.cpp
palace/models/materialoperator.hpp
palace/models/romoperator.cpp
palace/models/waveportoperator.cpp
palace/utils/timer.hpp

Added a few new categories for timing, including specific to linear solver vs. eigensolver vs. time stepping, and other related changes. This improves the organization and use of the timer classes throughout the code.

Updates to timer categories

---

docs/src/developer.md
docs/src/examples/cavity.md
docs/src/examples/rings.md
docs/src/examples/spheres.md
docs/src/install.md
docs/src/reference.md

NOTE: Waiting on some changes to timer categories and wave ports (see https://github.com/awslabs/palace/pull/191, https://github.com/awslabs/palace/pull/192)
Resolves #155, #187

Miscellaneous documentation fixes and improvements

---

palace/drivers/eigensolver.cpp
palace/linalg/arpack.cpp
palace/linalg/arpack.hpp
palace/linalg/divfree.cpp
palace/linalg/divfree.hpp
palace/linalg/eps.hpp
palace/linalg/errorestimator.cpp
palace/linalg/errorestimator.hpp
palace/linalg/hcurl.cpp
palace/linalg/hcurl.hpp
palace/linalg/slepc.cpp
palace/linalg/slepc.hpp
palace/models/materialoperator.cpp
palace/models/romoperator.cpp
palace/models/romoperator.hpp
palace/models/spaceoperator.cpp
palace/utils/geodata.cpp

In the limit which both systems are solved exactly, this has no effect. But it does affect the solution for some non-zero convergence tolerance.

Use complex-valued linear solvers even when operator is real-valued when the RHS is complex

---

.github/workflows/build-and-test-linux-aarch64.yml
.github/workflows/build-and-test-linux.yml
.github/workflows/build-and-test-macos.yml

See https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md

Update compiler versions for Github Actions

---

docs/src/config/boundaries.md
docs/src/config/problem.md

*Description of changes:* 
Adds a few missing commas to JSON blocks.

Add missing commas in config docs

---

examples/cpw/cpw.jl
examples/cpw/mesh/mesh.jl
examples/cylinder/cavity.jl
examples/cylinder/mesh/mesh.jl
examples/rings/mesh/mesh.jl

JuliaFormatter 2.0 causes the existing formatting to fail, this update fixes that.

JuliaFormatter v2.0 updates

---

docs/src/examples/coaxial.md

Fix for https://github.com/awslabs/palace/issues/303

Fix typo in Gaussian pulse doc

---

.github/workflows/build-and-test-linux.yml
.gitlab-ci.yml
cmake/ExternalGitTags.cmake
cmake/ExternalMFEM.cmake
extern/patch/mfem/patch_gmsh_parser_performance.diff
extern/patch/mfem/patch_gmsh_reader_periodic_bugfix.diff
extern/patch/mfem/patch_mesh_prism_vtu_fix.diff
extern/patch/mfem/patch_mesh_vis_dev.diff
extern/patch/mfem/patch_mfem_device_fixes.diff
extern/patch/mfem/patch_par_tet_mesh_fix_dev.diff
extern/patch/mumps/patch_build.diff
palace/models/timeoperator.cpp
spack/local/packages/palace/package.py

Fix for https://github.com/awslabs/palace/issues/313, and introduces https://github.com/mfem/mfem/pull/4484
- Updates AOCL to v5 in the CI
- Configures the gcc using update-alternatives to avoid where mpich is built with default version, thus using a different link time optimization.

Update magma git URL and all patches

---

cmake/ExternalMFEM.cmake
palace/drivers/basesolver.cpp
palace/drivers/basesolver.hpp
palace/drivers/drivensolver.cpp
palace/drivers/drivensolver.hpp
palace/drivers/eigensolver.cpp
palace/drivers/eigensolver.hpp
palace/drivers/electrostaticsolver.cpp
palace/drivers/electrostaticsolver.hpp
palace/drivers/magnetostaticsolver.cpp
palace/drivers/magnetostaticsolver.hpp
palace/drivers/transientsolver.cpp
palace/drivers/transientsolver.hpp
palace/models/postoperator.cpp
palace/models/postoperator.hpp
palace/utils/tablecsv.hpp

Modifications addressing the major feedback on `phdum/new_postpro`.

Suggested revisions for phdum/new_postpro

---

examples/cpw/cpw_coax_uniform.json
palace/fem/lumpedelement.cpp
palace/models/surfacepostoperator.cpp

Fixes https://github.com/awslabs/palace/issues/344

Bugfix for "-R" coaxial port

---

palace/models/materialoperator.cpp
palace/models/timeoperator.hpp
palace/utils/geodata.cpp
palace/utils/iodata.cpp

Fix some minor compiler warnings

Fix compiler warnings

---

CHANGELOG.md
palace/utils/meshio.cpp

Fixes bug in nastran reader uncovered in https://github.com/awslabs/palace/issues/337

Fix EOF bug in nastran mesh reader.

---

.github/workflows/build-and-test-linux.yml

* Expand the ubuntu CI to have arm and x86 separated
* Re-enable macos failing tests for testing

Testing expanded CI

---

docs/src/config/solver.md

Remove obsolete reference to `UseMultigrid`

---

spack/local/packages/palace/package.py

Fixes https://github.com/awslabs/palace/issues/430

Do not use cuda or rocm builds of superlu-dist or strumpack in spack build

---

.github/workflows/build-and-test-linux.yml

Testing removing constraint on intel oneAPI in CI

Remove constraint on intel oneAPI in CI

---

CHANGELOG.md
CMakeLists.txt
palace/CMakeLists.txt

Final changes for 0.14 release

Release 0.14.0

---

spack_repo/local/packages/palace/package.py

Parent spack PR - https://github.com/spack/spack-packages/pull/1146

Update local package.py with 0.14.0 tagged version.

---

palace/utils/configfile.cpp
scripts/schema/config/solver.json

Eigenmode simulations with N=0 are invalid, and we should verify.

Descriptive error message for N=0 in eigenmode

---

.github/workflows/docs.yml

Update docs pipeline to use buildcache
